version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres16_veiculo
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gerenciamento_combustivel
    ports:
      - "5434:5432"
    volumes:
      - pgdata_veiculo:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  backend:
    build: .
    container_name: gerenciamento-backend-veiculo
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: gerenciamento_combustivel
volumes:
  pgdata_veiculo:
