version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gerenciamento_combustivel
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    container_name: gerenciamento-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: gerenciamento_combustivel
volumes:
  pgdata:
